// Copyright (C) 2026-present Akitoshi Saeki
// SPDX-License-Identifier: AGPL-3.0-only

import { nanoid } from 'nanoid'

/**
 * Kinds of identifiers generated by the editor/renderer.
 *
 * Prefixes serve two purposes:
 * 1. Human-readable debugging (you can tell at a glance what kind of entity an
 *    ID belongs to when inspecting state or .neted.json files).
 * 2. Collision-avoidance across kinds — a node and a link can never share an ID
 *    even if nanoid were to theoretically produce the same suffix.
 */
export type IdKind = 'node' | 'sg' | 'link' | 'product' | 'inv' | 'port'

/**
 * Generate a fresh unique ID for the given entity kind.
 *
 * Collision probability for 10-char nanoid is negligible for editor-scale
 * workloads (~trillions of IDs before 1% collision chance).
 */
export function newId(kind: IdKind, size = 10): string {
  return `${kind}-${nanoid(size)}`
}
